name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf autotools-dev libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install buildozer cython kivy

      - name: Build with Buildozer
        run: |
          yes | buildozer init
          sed -i 's/package.name = myapp/package.name = deliverypro/' buildozer.spec
          sed -i 's/title = My Application/title = DeliveryPro/' buildozer.spec
          buildozer android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-delivery-app
          path: bin/*.apk
